name: location_n_pay
description: "A delivery tracking and payment reimbursement app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  flutter_background_service: ^5.1.0
  android_alarm_manager_plus: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
